SELECT "A" = "a" AS result;
SELECT "A" COLLATE UTF8MB4_BIN = "a" AS result;
SELECT "A" COLLATE UTF8MB4_0900_AS_CS = "a" AS result;
SELECT "A" COLLATE UTF8MB4_0900_AI_CI = "a" AS result;
SELECT "A" COLLATE UTF8MB4_0900_AI_CI = "a" COLLATE UTF8MB4_0900_AI_CI AS result;
SELECT "A" = "a" COLLATE UTF8MB4_0900_AI_CI AS result;
SELECT "A" = "a" COLLATE UTF8MB4_0900_AS_CS AS result;
SELECT "A" = "a" COLLATE UTF8MB4_BIN AS result;
SELECT "A" COLLATE UTF8MB4_BIN = "a" COLLATE UTF8MB4_0900_AI_CI AS result;

SELECT GREATEST("a","D","c") AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_BIN) AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_0900_AI_CI) AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_0900_AS_CS) AS result;
SELECT LEAST("a","D","c") AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_BIN) AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_0900_AI_CI) AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_0900_AS_CS) AS result;

SELECT GREATEST("a","D","c") AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_BIN) = "D" AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_0900_AI_CI) = "d" AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_0900_AS_CS) > "e" AS result;
SELECT GREATEST("a","D","c" COLLATE UTF8MB4_0900_AS_CS) > "c" AS result;
SELECT LEAST("a","D","c") AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_BIN) AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_0900_AI_CI) AS result;
SELECT LEAST("a","D","c" COLLATE UTF8MB4_0900_AS_CS) AS result;
